import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className='bg-gray-800'>
        <h1>Hello</h1>
      </nav>

      <main className={styles.main}>
        <div className="text-3xl text-green-600 p-2">
          <h1>Dashboard</h1>
        </div>
      </main>
    </>
  )
}
